### PR TITLE
close #43

### LINKED ISSUE #43: forgot password (low priority)
forgot pass page exists, need to make functionality

### PR DESCRIPTION
**Pull request by michaeldub**
Captcha Fix
Forgot mail link fix.

### CODE REVIEW

**Review by SheyDenis — CHANGES_REQUESTED** [review]
Please move the "script" tags above the "@endsection" tag.
Otherwise it will not be included in the page.

**Comment by SheyDenis** [comment]
Also what does "Forgot mail link fix." mean?

**Comment by michaeldub** [comment]
previously , the change password mail was sent with the link localhost -  resulted in error when trying to acess it - the fix is to change the adress of the link to 127.0.0.1 and it works.

probably needs to be updated to the ip adress of the server for presentation.

**Review by SheyDenis — APPROVED** [review]

**Comment by SheyDenis** [comment]
I see no mention of the link in the code, but it's low priority so ok.
Also I didn't actually test any of this.

**Pull request merged**
